# Generated by Django 5.0.2 on 2024-02-25 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('card_number', models.IntegerField()),
                ('is_suspend', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('community_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_admin', to=settings.AUTH_USER_MODEL, verbose_name='Администратор сообщества')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('invite_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='users.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
